import 'package:freezed_annotation/freezed_annotation.dart';

part 'completed_weighing.freezed.dart';
part 'completed_weighing.g.dart';

@freezed
abstract class CompletedWeighing with _$CompletedWeighing {
  const factory CompletedWeighing({
    @JsonKey(name: 'id') String? id,
    @JsonKey(name: 'syncID') String? syncID,
    @JsonKey(name: 'soPhieu') String? ticketNumber,
    @JsonKey(name: 'kyHieuPhieuCan') String? ticketSymbol,
    @JsonKey(name: 'bienSoDangKy') String? registrationPlate,
    @JsonKey(name: 'cardNumber') String? cardNumber,
    @JsonKey(name: 'ngayCan1') String? date1,
    @JsonKey(name: 'gioCan1') String? time1,
    @JsonKey(name: 'ngayCan2') String? date2,
    @JsonKey(name: 'gioCan2') String? time2,
    @JsonKey(name: 'bienSo11') String? licensePlate1,
    @JsonKey(name: 'bienSo12') String? licensePlate12,
    @JsonKey(name: 'bienSo21') String? licensePlate2,
    @JsonKey(name: 'bienSo22') String? licensePlate22,
    @JsonKey(name: 'khoiLuongCan1') String? weight1,
    @JsonKey(name: 'khoiLuongCan2') String? weight2,
    @JsonKey(name: 'khoiLuongHang') String? netWeight,
    @JsonKey(name: 'khoiLuongGiamTru') String? deductionWeight,
    @JsonKey(name: 'khoiLuongGiamTru2') String? deductionWeight2,
    @JsonKey(name: 'tyLeTapChat') String? impurityRatio,
    @JsonKey(name: 'nhapKhoiLuongTapChat') String? impurityWeight,
    @JsonKey(name: 'khoiLuongThanhToan') String? paymentWeight,
    @JsonKey(name: 'khoiLuongHangQD') String? convertedWeight,
    @JsonKey(name: 'donvi_Kg') String? unit,
    @JsonKey(name: 'chatLuongHangHoa') String? goodsQuality,
    @JsonKey(name: 'donGia') String? price,
    @JsonKey(name: 'thanhTien') String? totalPrice,
    @JsonKey(name: 'thanhToan') String? paymentStatus,
    @JsonKey(name: 'maKhachHang') String? customerCode,
    @JsonKey(name: 'khachHang') String? customerName,
    @JsonKey(name: 'maLoaiHang') String? productCode,
    @JsonKey(name: 'loaiHang') String? productName,
    @JsonKey(name: 'khoHang') String? warehouseName,
    @JsonKey(name: 'nguonGoc') String? origin,
    @JsonKey(name: 'kieuCan') String? weighingType,
    @JsonKey(name: 'nguoiCan1') String? weigher1,
    @JsonKey(name: 'nguoiCan2') String? weigher2,
    @JsonKey(name: 'tenLaiXe') String? driverName,
    @JsonKey(name: 'cmndLaiXe') String? driverIdCard,
    @JsonKey(name: 'soChungTu') String? documentNumber,
    @JsonKey(name: 'quyCach') String? specification,
    @JsonKey(name: 'maDonHangAPI') String? apiOrderCode,
    @JsonKey(name: 'heThongDangKy') String? registrationSystem,
    @JsonKey(name: 'maKho') String? warehouseCode,
    @JsonKey(name: 'maChuyen') String? tripCode,
    @JsonKey(name: 'nhaXe') String? transportCompany,
    @JsonKey(name: 'giayPhepAnToan') String? safetyPermit,
    @JsonKey(name: 'ngayHetHanGPAT') String? safetyPermitExpiry,
    @JsonKey(name: 'ghiChu') String? note,
    @JsonKey(name: 'thoiTiet') String? weather,
    @JsonKey(name: 'mayBam') String? shredder,
    @JsonKey(name: 'congNhan') String? worker,
    @JsonKey(name: 'nhanVienThuMua') String? purchaser,
    @JsonKey(name: 'doAm') String? humidity,
    @JsonKey(name: 'chatLuongHangHoa2') String? goodsQuality2,
    @JsonKey(name: 'chatLuongSay') String? dryingQuality,
    @JsonKey(name: 'xuong') String? factory,
    @JsonKey(name: 'VehicleImagePath11') String? vehicleImagePath11,
    @JsonKey(name: 'PanoramaImagePath11') String? panoramaImagePath11,
    @JsonKey(name: 'VehicleImagePath12') String? vehicleImagePath12,
    @JsonKey(name: 'PanoramaImagePath12') String? panoramaImagePath12,
    @JsonKey(name: 'VehicleImagePath21') String? vehicleImagePath21,
    @JsonKey(name: 'PanoramaImagePath21') String? panoramaImagePath21,
    @JsonKey(name: 'VehicleImagePath22') String? vehicleImagePath22,
    @JsonKey(name: 'PanoramaImagePath22') String? panoramaImagePath22,
  }) = _CompletedWeighing;

  factory CompletedWeighing.fromJson(Map<String, dynamic> json) =>
      _$CompletedWeighingFromJson(json);
}
